name: ksa_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.1.0  # تحقق من أحدث إصدار في pub.dev
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.11  # إضافة مكتبة shared_preferences
  intl: ^0.19.0  # تحديث مكتبة intl
  flutter_localizations:  # إضافة مكتبة localizations
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/  # تأكد من أن الصور موجودة داخل مجلد assets
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-VariableFont_slnt,wght.ttf
